apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ci-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ci-registry
    app.kubernetes.io/part-of: registry
  name: ci-registry
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ci-registry
status:
  loadBalancer: {}
