apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tests-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tests-registry
    app.kubernetes.io/part-of: registry
  name: tests-registry
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: tests-registry
status:
  loadBalancer: {}
